add_newline = false

[character]
success_symbol = "[]()"
error_symbol = "[]()"

[shell]
disabled = true

[username]
style_user = "fg:97 bold"
show_always = true
format = "[$user]($style) "

[hostname]
ssh_only = false
style = "fg:97 bold"
format = "at [$hostname]($style) "

[directory]
truncation_length = 0
truncate_to_repo = false
style = "fg:97 bold"
format = "in [$path]($style) "

[git_branch]
style = "fg:97 bold"
format = "on [$symbol$branch]($style) "

[cmd_duration]
disabled = true

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[deno]
disabled = true

[cmake]
disabled = true

[dart]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[helm]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
