format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill using $shell\
$line_break\
$character"""

right_format = ""
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[]()"
error_symbol = "[]()"
vicmd_symbol = "[]()"

[cmake]
disabled = true

[cobol]
disabled = true

[cmd_duration]
disabled = true

[conda]
disabled = true

[custom]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false
style = "fg:97 bold"
format = "in [$path]($style) "

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[fill]
symbol = " "
style = "bold black"

[gcloud]
disabled = true

[git_branch]
style = "fg:97 bold"
format = "on [$symbol$branch]($style) "

[git_metrics]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[hostname]
ssh_only = false
style = "fg:97 bold"
format = "at [$hostname]($style) "

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = false

[lua]
disabled = true

[memory_usage]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
powershell_indicator = "powershell"
format = "[$indicator](fg:97 bold) "

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[username]
style_user = "fg:97 bold"
show_always = true
format = "[$user]($style) "

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
