format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill using $shell\
$line_break\
$character"""

right_format = ""
add_newline = false

[character]
success_symbol = "[]()"
error_symbol = "[]()"
vicmd_symbol = "[]()"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "fg:197 bold"
format = "in [$path]($style) "

[fill]
symbol = " "
style = "bold black"

[git_branch]
style = "fg:197 bold"
format = "on [$symbol$branch]($style) "

[hostname]
ssh_only = false
style = "fg:197 bold"
format = "at [$hostname]($style) "

[shell]
disabled = false
bash_indicator = "bash"
fish_indicator = "fish"
powershell_indicator = "powershell"
format = "[$indicator](fg:197 bold) "

[username]
style_user = "fg:197 bold"
show_always = true
format = "[$user]($style) "
