# Basic options
default_keybindings = false
notify = false
volnorm = true
volnorm_pregain = -3
flip_status_indicators = true

[saved_state]
shuffle = true

[keybindings]
"Enter" = "play"
"Space" = "playpause"

"Right" = "seek +1000"
"Left" = "seek -1000"

"+" = "volup 1"
"-" = "voldown 1"
"n" = "next"
"p" = "previous"

"A" = "goto album"
"a" = "goto artist"

"O" = "open current"
"o" = "open selected"
"l" = "open selected"
"h" = "back"
"Esc" = "back"

"q" = "quit"
"?" = "help"
"U" = "update"

"H" = "move left 1"
"L" = "move right 1"
"j" = "move down 1"
"J" = "move down 5"
"k" = "move up 1"
"K" = "move up 5"
"g" = "move top"
"G" = "move bottom"

"Ctrl+q" = "focus queue"
"Ctrl+s" = "focus search"
"Ctrl+l" = "focus library"

"c" = "clear"
"r" = "repeat"
"s" = "shuffle"
"S" = "save"
"D" = "delete"

[theme]
background = "default"
primary = "default"
secondary = "light black"
title = "magenta"
playing = "magenta"
playing_selected = "magenta"
highlight = "default"
highlight_bg = "#2a2a2a"
error = "light white"
error_bg = "red"
statusbar = "light white"
statusbar_progress = "magenta"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"
