#!/usr/bin/env bash

# This userscript writes the current url into a given file. If the 
# current url is already in the file, it will be deleted instead.
# If the string 'edit' is passed as the first argument, the file
# will be opened for editing.

if [ -z "$QUTE_FIFO" ] ; then
    cat 1>&2 <<EOF
Error: $0 can not be run as a standalone script.

It is a qutebrowser userscript. In order to use it, call it using
'spawn --userscript' as described in qute://help/userscripts.html
EOF
    exit 1
fi

bookmark_file="$HOME/.local/share/bookmarks"
urls=$(cat $bookmark_file | awk '{print $NF}')

if [ "$1" = "edit" ]; then
    printf "message-info 'Opening $bookmark_file with $EDITOR'" > "$QUTE_FIFO"
    $TERMINAL $EDITOR "$bookmark_file"
elif [ ! -z "$1" ]; then
    sed -i "\|$QUTE_URL|d" "$bookmark_file"
    printf '%s\n' "$1 - $QUTE_URL" >> "$bookmark_file"
    printf "message-info 'Page added to bookmarks.'" > "$QUTE_FIFO"
else
    for url in ${urls[@]}; do
        if [ "$QUTE_URL" = "$url" ]; then
            sed -i "\|$url|d" "$bookmark_file"
            printf "message-info 'Page removed from bookmarks.'" > "$QUTE_FIFO"
            exit 0
        fi
    done
    printf '%s\n' "$QUTE_URL $*" >> "$bookmark_file"
    printf "message-info 'Page added to bookmarks.'" > "$QUTE_FIFO"
fi

