#!/bin/sh

# This script kills light-locker if it is running, otherwise it starts it 
# in the background, so the screen will be locked after inactivity

if [ -n "$(pidof light-locker)" ]; then
    killall light-locker; dunstify --replace=1 "Light-locker disabled"; exit 1
fi

dunstify --replace=1 "Light-locker enabled"; light-locker --lock-after-screensaver=120 &
