#!/bin/sh

icon=""

capacity=$(cat /sys/class/power_supply/BAT1/capacity) || exit
status=$(cat /sys/class/power_supply/BAT1/status)

if [ "$capacity" -le 75 ]; then
    icon=""
elif [ "$capacity" -le 50 ]; then
    icon=""
elif [ "$capacity" -le 30 ]; then
    icon=""
elif [ "$capacity" -le 20 ]; then
    icon=""
fi
 
echo "$icon"

case $BUTTON in
    1) dunstify --replace=1 "Battery: $capacity%" "$status";;
esac
