#!/bin/sh

case "$(xset -q|grep LED| awk '{ print $10 }')" in
  "00000002") KBD="us" ;;
  "00001002") KBD="hu" ;;
  *) KBD="unknown" ;;
esac

echo " $KBD"

case $BUTTON in
    1) dunstify --replace=1 "Keyboard layout" "Alt+sapce to toggle";;
esac
