#!/bin/sh

case $BUTTON in
    1) dunstify --replace=1 "Light-locker status" "Mod+ctrl+l to toggle"
esac

# This script checks if light-locker is running, and prints an appropriate indicator

if [ -n "$(pidof light-locker)" ]; then
    printf "%s", " on"; exit 1
fi

printf "%s", " off"

