#!/bin/sh

volstat="$(amixer get Master)"

echo "$volstat" | grep "\[off\]" >/dev/null && printf "\\n" && exit

vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed 's/[^0-9]*//g')

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s\\n" "$icon $vol%"

dunstify --replace=1 "Volume $vol%"

case $BUTTON in
    1) dunstify --replace=1 "Volume $vol%" "Right click to open alsamixer";;
    3) st -e alsamixer;;
esac

