#!/bin/sh

# This script uses pactl to get the volume level and display it in
# the form of a notification and display an appropriate icon in the 
# status bar.

sinkinfo="$(pactl list sinks | grep 'Name\|Mute\|Volume:')"

echo "$sinkinfo" | grep "Mute: yes" > /dev/null && printf "\\n" && exit

vol=$(echo "$sinkinfo" | grep "front-left" | awk '{ print $5 }' | tr -d "%")

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s\\n" "$icon"

dunstify --replace=1 "Volume $vol%"

case $BUTTON in
    1) dunstify --replace=1 "Volume $vol%" "Right click to open alsamixer";;
    3) st -e alsamixer & disown;;
esac

