#!/bin/sh

volstat="$(amixer get Master)"

echo "$volstat" | grep "\[off\]" >/dev/null && printf "\\n" && exit

vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed 's/[^0-9]*//g')

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s %s%%\\n" "$icon" "$vol"

dunstify --replace=1 "Volume $vol%"
